server:
  port: 9999

spring:
  profiles:
    active: mysqldev
  datasource:
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8"
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    initialSize: 0
    maxActive: 200
    maxIdle: 20
    minIdle: 0
    maxWait: 300000
    removeAbandoned: true
    removeAbandonedTimeout: 300
    logAbandoned: false
    validationQuery: SELECT 1
    testOnBorrow: true
    poolPreparedStatements: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    openInView: true
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
